/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package finalprojectsem1.pos.view;

/**
 *
 * @author Acer
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btnResultDutyPoint = new javax.swing.JButton();
        btnDutyPoint = new javax.swing.JButton();
        btnEmployeeDuty = new javax.swing.JButton();
        btnEmployee = new javax.swing.JButton();
        lblHeading = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lblDetails = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(69, 90, 100));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(96, 125, 139));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnResultDutyPoint.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnResultDutyPoint.setForeground(new java.awt.Color(204, 255, 255));
        btnResultDutyPoint.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnResultDutyPointMouseMoved(evt);
            }
        });
        btnResultDutyPoint.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnResultDutyPointMouseExited(evt);
            }
        });
        btnResultDutyPoint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResultDutyPointActionPerformed(evt);
            }
        });
        jPanel3.add(btnResultDutyPoint, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, 170, 160));

        btnDutyPoint.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnDutyPoint.setForeground(new java.awt.Color(204, 255, 255));
        btnDutyPoint.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnDutyPointMouseMoved(evt);
            }
        });
        btnDutyPoint.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDutyPointMouseExited(evt);
            }
        });
        btnDutyPoint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDutyPointActionPerformed(evt);
            }
        });
        jPanel3.add(btnDutyPoint, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 170, 160));

        btnEmployeeDuty.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnEmployeeDuty.setForeground(new java.awt.Color(204, 255, 255));
        btnEmployeeDuty.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnEmployeeDutyMouseMoved(evt);
            }
        });
        btnEmployeeDuty.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEmployeeDutyMouseExited(evt);
            }
        });
        btnEmployeeDuty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmployeeDutyActionPerformed(evt);
            }
        });
        jPanel3.add(btnEmployeeDuty, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 170, 160));

        btnEmployee.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnEmployee.setForeground(new java.awt.Color(204, 255, 255));
        btnEmployee.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnEmployeeMouseMoved(evt);
            }
        });
        btnEmployee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEmployeeMouseExited(evt);
            }
        });
        btnEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmployeeActionPerformed(evt);
            }
        });
        jPanel3.add(btnEmployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 170, 160));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 650));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 660));

        lblHeading.setBackground(new java.awt.Color(204, 204, 204));
        lblHeading.setFont(new java.awt.Font("Vineta BT", 0, 36)); // NOI18N
        lblHeading.setForeground(new java.awt.Color(96, 125, 139));
        lblHeading.setText("Please select one button from left side");
        jPanel1.add(lblHeading, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, 990, 89));

        jPanel4.setBackground(new java.awt.Color(69, 90, 100));

        lblDetails.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblDetails.setForeground(new java.awt.Color(255, 255, 255));

        jButton1.setText("Employee History");

        jButton2.setText("Wach Employee");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Employee Choice");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDetails, javax.swing.GroupLayout.DEFAULT_SIZE, 12, Short.MAX_VALUE)
                .addGap(44, 44, 44)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lblDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(143, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(126, 126, 126))))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, 720, 460));

        jPanel6.setBackground(new java.awt.Color(69, 90, 100));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1090, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 1090, 20));

        jPanel7.setBackground(new java.awt.Color(69, 90, 100));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1350, 20, 20, 640));

        jPanel8.setBackground(new java.awt.Color(69, 90, 100));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1070, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 640, 1070, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1373, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 677, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEmployeeDutyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmployeeDutyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEmployeeDutyActionPerformed

    private void btnDutyPointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDutyPointActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDutyPointActionPerformed

    private void btnResultDutyPointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResultDutyPointActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnResultDutyPointActionPerformed

    private void btnEmployeeMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEmployeeMouseMoved
      lblHeading.setText("EMPLOYEE DETAILS");
      lblDetails.setText("Employee update,Employee delete,Employee parsnal");

      btnEmployee.setIcon(new javax.swing.ImageIcon("C:\\Users\\Vinnie\\Downloads\\icons8-male-user-96.png"));
    }//GEN-LAST:event_btnEmployeeMouseMoved

    private void btnEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmployeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEmployeeActionPerformed

    private void btnEmployeeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEmployeeMouseExited
      lblHeading.setText("Please select one button from left side");
      btnEmployee.setIcon(new javax.swing.ImageIcon("C:\\Users\\Vinnie\\Downloads\\icons8-male-user-48.png"));
    }//GEN-LAST:event_btnEmployeeMouseExited

    private void btnEmployeeDutyMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEmployeeDutyMouseMoved
      lblHeading.setText("HISTORY OF EMPLOYEE");
      lblDetails.setText("Early workplaces of employee and can see when left duty points and when join the duty point");
      btnEmployeeDuty.setIcon(new javax.swing.ImageIcon("C:\\Users\\Vinnie\\Downloads\\icons8-product-documents-96.png"));
    }//GEN-LAST:event_btnEmployeeDutyMouseMoved

    private void btnEmployeeDutyMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEmployeeDutyMouseExited
      lblHeading.setText("Please select one button from left side");
      btnEmployeeDuty.setIcon(new javax.swing.ImageIcon("C:\\Users\\Vinnie\\Downloads\\icons8-product-documents-48.png")); 
    }//GEN-LAST:event_btnEmployeeDutyMouseExited

    private void btnDutyPointMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDutyPointMouseMoved
        lblHeading.setText("DUTY POINT");
      lblDetails.setText("Places that employee work.Update,delete and add  "
              + "directorate,grouptype of the duty point,port type");
       btnDutyPoint.setIcon(new javax.swing.ImageIcon("C:\\Users\\Vinnie\\Downloads\\icons8-department-96.png"));
    }//GEN-LAST:event_btnDutyPointMouseMoved

    private void btnDutyPointMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDutyPointMouseExited
         lblHeading.setText("Please select one button from left side");
          btnDutyPoint.setIcon(new javax.swing.ImageIcon("C:\\Users\\Vinnie\\Downloads\\icons8-department-48.png"));
    }//GEN-LAST:event_btnDutyPointMouseExited

    private void btnResultDutyPointMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnResultDutyPointMouseMoved
       lblHeading.setText("MAKE TRANSFAR");
      lblDetails.setText("What you want to do..Make transfar of employee");
       btnResultDutyPoint.setIcon(new javax.swing.ImageIcon("C:\\Users\\Vinnie\\Downloads\\icons8-office-96.png"));
    }//GEN-LAST:event_btnResultDutyPointMouseMoved

    private void btnResultDutyPointMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnResultDutyPointMouseExited
         lblHeading.setText("Please select one button from left side");
         btnResultDutyPoint.setIcon(new javax.swing.ImageIcon("C:\\Users\\Vinnie\\Downloads\\icons8-office-48.png"));
    }//GEN-LAST:event_btnResultDutyPointMouseExited

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDutyPoint;
    private javax.swing.JButton btnEmployee;
    private javax.swing.JButton btnEmployeeDuty;
    private javax.swing.JButton btnResultDutyPoint;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JLabel lblDetails;
    private javax.swing.JLabel lblHeading;
    // End of variables declaration//GEN-END:variables
}
